### ISSUE TITLE
Substance Index 404

### ISSUE THREAD

**Issue by MikeJerred** [effectindex/EffectIndex#60]
This page is not found: https://effectindex.com/substances/
It is linked to from the homepage in the "Substance Summaries" box.

**Comment by 5HT2** [comment]
Well it looks like this commit removed the link in August 2021 but it somehow never got applied to the master branch.
https://github.com/effectindex/EffectIndex/commit/38827c2572258bb94649b44c52d7f9c64dc9d0c5

**Comment by 5HT2** [comment]
Thanks!
